### ISSUE TITLE
Implement more error checking and logging

### ISSUE THREAD

**Issue by MonJamp** [JethroDevon/revengeMusic#29]

**Comment by MonJamp** [comment]
Someone has to do the tedious stuff :stuck_out_tongue:

**Comment by JethroDevon** [comment]
I been doing uni work for months, cant wait to do my own tediuos stuff.
Can't wait to get on my own projects again :D

**Comment by MonJamp** [comment]
Same. It's been a while since I've even had free time to work on any coding project. So long that I forgot that I actually started to work on this issue a while ago.

**Comment by Dyrand** [comment]
I think I'm ready for a project too, after doing uni projects. Might chip in on revengeMusic again.

**Comment by JethroDevon** [comment]
Yeah it has a lot of potential, I like the idea of being a flexible console program so much so that GUIs could be made seperatley

________________________________
