### ISSUE TITLE
update for new dependencies

### ISSUE THREAD

**Issue by JethroDevon** [JethroDevon/revengeMusic#30]
libboost_system.so.1.60.0 is out of date upgrade program to support boost-1.61.0-2

**Comment by MonJamp** [comment]
The latest version of libboost you can get from default Ubuntu 16.04 repositories is 1.58, so I'm not sure if it's necessary to update the requirement.

**Comment by MonJamp** [comment]
I'm currently using boost 1.64.0 on Windows and it's not causing any issues when compiling. So I'm not sure if there's any benefit to making a newer version of boost a dependency.
