### ISSUE TITLE
Incompatible with Windows

### ISSUE THREAD

**Issue by MonJamp** [JethroDevon/revengeMusic#4]
A lot of code is only compatible in Linux although it should be trivial to port to Windows.
Currently the only part that has to be ported to Windows is the use of named pipes and checking if there are multiple instances of the program.
Resources:
- [Named Pipes in Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365590%28v=vs.85%29.aspx)
- [Checking for multiple instances](http://stackoverflow.com/questions/8799646/preventing-multiple-instances-of-my-application)

**Comment by monsterjamp** [comment]
I don't think this has been solved yet.
