### ISSUE TITLE
Interprocess communication not working fully

### ISSUE THREAD

**Issue by Dyrand** [JethroDevon/revengeMusic#43]
~~It seems as if a 2nd process can determine that another process is running, but the messages don't appear to be reaching the other process.~~

Often times the client sends a message to itself because all instances read from the same message queue.

Suggested solution
---------------------
Create two queues:

- one for sending from the client to the player
- one for sending from the player to the client

**Comment by MonJamp** [comment]
I agree, we should have 2 queues.

Also just so it'll be less confusing going forward, we should use this naming scheme for the processes:
"Player" - the process plays the music
"Client" - the process that sends commands to the player
